<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Vehicle::insert([
            // ===== CENTRAL AUTO SHOP (Phnom Penh) =====
            [
                'vehicle_id' => 'veh_001',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Giant Escape 3',
                'shop_id' => 'central_auto_shop',
                'brand' => 'Giant',
                'model' => 'Escape 3',
                'year' => 2020,
                'color' => 'Red',
                'rental_price_per_day' => 5.00,
                'description' => 'A reliable and comfortable city bike perfect for Phnom Penh streets.',
            ],
            [
                'vehicle_id' => 'veh_002',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Trek FX 1',
                'shop_id' => 'central_auto_shop',
                'brand' => 'Trek',
                'model' => 'FX 1',
                'year' => 2021,
                'color' => 'Blue',
                'rental_price_per_day' => 6.00,
                'description' => 'A lightweight hybrid bike built for fitness and commuting.',
            ],
            [
                'vehicle_id' => 'veh_003',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Honda CB125R',
                'shop_id' => 'central_auto_shop',
                'brand' => 'Honda',
                'model' => 'CB125R',
                'year' => 2022,
                'color' => 'Black',
                'rental_price_per_day' => 10.00,
                'description' => 'Compact motorcycle with great performance for daily rides in Phnom Penh.',
            ],
            [
                'vehicle_id' => 'veh_004',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Yamaha XSR155',
                'shop_id' => 'central_auto_shop',
                'brand' => 'Yamaha',
                'model' => 'XSR155',
                'year' => 2023,
                'color' => 'Silver',
                'rental_price_per_day' => 11.50,
                'description' => 'Stylish motorcycle perfect for short trips and city cruising.',
            ],

            // ===== COASTAL RIDES (Sihanoukville) =====
            [
                'vehicle_id' => 'veh_005',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Specialized Sirrus 2.0',
                'shop_id' => 'coastal_rides',
                'brand' => 'Specialized',
                'model' => 'Sirrus 2.0',
                'year' => 2021,
                'color' => 'White',
                'rental_price_per_day' => 5.50,
                'description' => 'A smooth hybrid bike ideal for coastal paths and flat roads.',
            ],
            [
                'vehicle_id' => 'veh_006',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Cannondale Quick 4',
                'shop_id' => 'coastal_rides',
                'brand' => 'Cannondale',
                'model' => 'Quick 4',
                'year' => 2020,
                'color' => 'Green',
                'rental_price_per_day' => 6.50,
                'description' => 'Light and responsive city bicycle for seaside rides.',
            ],
            [
                'vehicle_id' => 'veh_007',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Honda CB500X',
                'shop_id' => 'coastal_rides',
                'brand' => 'Honda',
                'model' => 'CB500X',
                'year' => 2021,
                'color' => 'Black',
                'rental_price_per_day' => 12.00,
                'description' => 'Adventure-ready motorcycle for long coastal roads.',
            ],
            [
                'vehicle_id' => 'veh_008',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Suzuki Raider R150',
                'shop_id' => 'coastal_rides',
                'brand' => 'Suzuki',
                'model' => 'Raider R150',
                'year' => 2020,
                'color' => 'Blue',
                'rental_price_per_day' => 9.00,
                'description' => 'Sporty and lightweight motorcycle great for city cruising by the beach.',
            ],

            // ===== HERITAGE MOTORS (Siem Reap) =====
            [
                'vehicle_id' => 'veh_009',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Trek Domane AL 2',
                'shop_id' => 'heritage_motors',
                'brand' => 'Trek',
                'model' => 'Domane AL 2',
                'year' => 2019,
                'color' => 'White',
                'rental_price_per_day' => 6.00,
                'description' => 'Endurance bike perfect for exploring Siem Reap’s temples.',
            ],
            [
                'vehicle_id' => 'veh_010',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Giant Contend 3',
                'shop_id' => 'heritage_motors',
                'brand' => 'Giant',
                'model' => 'Contend 3',
                'year' => 2022,
                'color' => 'Gray',
                'rental_price_per_day' => 7.00,
                'description' => 'Lightweight road bike designed for speed and comfort.',
            ],
            [
                'vehicle_id' => 'veh_011',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Yamaha MT-15',
                'shop_id' => 'heritage_motors',
                'brand' => 'Yamaha',
                'model' => 'MT-15',
                'year' => 2021,
                'color' => 'Blue',
                'rental_price_per_day' => 10.50,
                'description' => 'Naked sports bike with a powerful engine for smooth temple routes.',
            ],
            [
                'vehicle_id' => 'veh_012',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Honda Rebel 300',
                'shop_id' => 'heritage_motors',
                'brand' => 'Honda',
                'model' => 'Rebel 300',
                'year' => 2020,
                'color' => 'Gray',
                'rental_price_per_day' => 11.00,
                'description' => 'Classic cruiser motorcycle ideal for comfortable sightseeing rides.',
            ],

            // ===== KAMPOT CRUISERS (Kampot) =====
            [
                'vehicle_id' => 'veh_013',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Merida Crossway 100',
                'shop_id' => 'kampot_cruisers',
                'brand' => 'Merida',
                'model' => 'Crossway 100',
                'year' => 2021,
                'color' => 'Silver',
                'rental_price_per_day' => 5.50,
                'description' => 'Comfortable hybrid bicycle ideal for Kampot’s riverside trails.',
            ],
            [
                'vehicle_id' => 'veh_014',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Polygon Heist 3',
                'shop_id' => 'kampot_cruisers',
                'brand' => 'Polygon',
                'model' => 'Heist 3',
                'year' => 2022,
                'color' => 'Black',
                'rental_price_per_day' => 6.50,
                'description' => 'Durable city bike for relaxed countryside rides.',
            ],
            [
                'vehicle_id' => 'veh_015',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Yamaha Aerox 155',
                'shop_id' => 'kampot_cruisers',
                'brand' => 'Yamaha',
                'model' => 'Aerox 155',
                'year' => 2022,
                'color' => 'Red',
                'rental_price_per_day' => 8.50,
                'description' => 'Automatic scooter perfect for quick trips around Kampot.',
            ],
            [
                'vehicle_id' => 'veh_016',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Honda PCX 160',
                'shop_id' => 'kampot_cruisers',
                'brand' => 'Honda',
                'model' => 'PCX 160',
                'year' => 2023,
                'color' => 'White',
                'rental_price_per_day' => 9.50,
                'description' => 'Luxury scooter for smooth, quiet city cruising.',
            ],

            // ===== BATTAMBANG WHEELS (Battambang) =====
            [
                'vehicle_id' => 'veh_017',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Cube Nature Pro',
                'shop_id' => 'battambang_wheels',
                'brand' => 'Cube',
                'model' => 'Nature Pro',
                'year' => 2021,
                'color' => 'Gray',
                'rental_price_per_day' => 6.00,
                'description' => 'Durable hybrid bike for Battambang’s charming countryside roads.',
            ],
            [
                'vehicle_id' => 'veh_018',
                'vehicle_type_id' => 'bicycle',
                'vehicle_name' => 'Scott Sub Cross 50',
                'shop_id' => 'battambang_wheels',
                'brand' => 'Scott',
                'model' => 'Sub Cross 50',
                'year' => 2022,
                'color' => 'Orange',
                'rental_price_per_day' => 6.50,
                'description' => 'Reliable and versatile bicycle designed for touring Battambang.',
            ],
            [
                'vehicle_id' => 'veh_019',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Honda Click 150i',
                'shop_id' => 'battambang_wheels',
                'brand' => 'Honda',
                'model' => 'Click 150i',
                'year' => 2021,
                'color' => 'Blue',
                'rental_price_per_day' => 8.00,
                'description' => 'Compact and fuel-efficient motorcycle for quick trips around town.',
            ],
            [
                'vehicle_id' => 'veh_020',
                'vehicle_type_id' => 'motorcycle',
                'vehicle_name' => 'Yamaha Mio 125',
                'shop_id' => 'battambang_wheels',
                'brand' => 'Yamaha',
                'model' => 'Mio 125',
                'year' => 2020,
                'color' => 'Black',
                'rental_price_per_day' => 7.50,
                'description' => 'Easy-to-ride automatic scooter for casual rides across Battambang.',
            ],
        ]);
    }
}
